name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string
      release_notes:
        description: 'Additional release notes (optional)'
        required: false
        type: string

jobs:
  create-release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest build artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          name: popbot-win64
          path: artifacts

      - name: Rename executable
        run: |
          cd artifacts
          for file in *.exe; do
            new_name=$(echo "$file" | sed "s/1.0.0/${{ github.event.inputs.version }}/g")
            mv "$file" "$new_name"
          done

      - name: Generate release notes
        id: release_notes
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          body: |
            ## What's Changed
            
            ${{ github.event.inputs.release_notes }}
            
            ### Full Changelog
            ${{ github.event.repository_url }}/compare/v${{ github.event.inputs.version }}...main
          files: artifacts/*.exe